<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
	  <Nullable>enable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	  <ContainerRepository>fionasapphire/squares-solver</ContainerRepository>
	  <ContainerFamily>noble-chiseled-extra</ContainerFamily>
	  <ContainerRegistry>docker.io</ContainerRegistry>
	  <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\ElectricFox.SquaresSolver\ElectricFox.SquaresSolver.csproj" />
  </ItemGroup>

</Project>
